import '../../../closet/data/models/clothing_item.dart';

/// Represents a single outfit suggestion generated by the AI stylist.
/// Contains the garments involved, AI reasoning, and optional try-on result.
class OutfitSuggestion {
  final String name;
  final String description;
  final String styleTip;
  final List<String> itemIds;
  final List<ClothingItem> items;
  String? tryOnImageUrl;

  OutfitSuggestion({
    required this.name,
    required this.description,
    required this.styleTip,
    required this.itemIds,
    required this.items,
    this.tryOnImageUrl,
  });

  /// The primary garment for virtual try-on (outermost/top layer).
  ClothingItem get primaryGarment => items.first;

  factory OutfitSuggestion.fromJson(
    Map<String, dynamic> json,
    List<ClothingItem> allClothes,
  ) {
    final ids = (json['item_ids'] as List<dynamic>)
        .map((e) => e.toString())
        .toList();

    final matchedItems = ids
        .map((id) => allClothes.where((c) => c.id.toString() == id))
        .where((matches) => matches.isNotEmpty)
        .map((matches) => matches.first)
        .toList();

    // If no items matched, use the first available garment
    if (matchedItems.isEmpty && allClothes.isNotEmpty) {
      matchedItems.add(allClothes.first);
    }

    return OutfitSuggestion(
      name: json['name']?.toString() ?? 'Outfit',
      description: json['description']?.toString() ?? '',
      styleTip: json['style_tip']?.toString() ?? '',
      itemIds: ids,
      items: matchedItems,
    );
  }
}
